import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
window:
  padding:
    x: 10
    y: 10
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.8
  startup_mode: Windowed
  decorations: none

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: FiraCode Nerd Font Mono 
    style:  Regular
  bold:
    family: FiraCode Nerd Font Mono
    style:  Bold
  size: 15
draw_bold_text_with_bright_colors: true


selection:
  save_to_clipboard: false

shell:
  program: /usr/bin/zsh

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

